[package]
name = "h1emu-core"
version = "0.4.0"
edition = "2018"
[dependencies]
wasm-bindgen = "0.2.45"
rand = { version = "0.6.5", features = ["wasm-bindgen"] }
[lib]
crate-type = ["cdylib"]
[profile.release]
lto = true
opt-level = 3