[package]
name = "h1emu-core"
version = "0.7.0"
edition = "2021"
description = "Utility library used in h1emu."
license = "BSD-3-Clause"
repository = "https://github.com/H1emu/H1emu-core"
readme="README.md"

[dependencies]
wasm-bindgen = "0.2.79"
getrandom = { version = "0.2.5", features = ["js"] }
rand = "0.8.5"
byteorder = "1.4.3"
wee_alloc = "0.4.5"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "lib-bench"
harness = false

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 3

[package.metadata.wasm-pack.profile.release]
# `wasm-opt`. For example `['-Os']` would optimize for size while `['-O4']`
wasm-opt = ['-O4']

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false
