[package]
name = "h1emu-core"
version = "0.6.3"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.78"
getrandom = { version = "0.2.3", features = ["js"] }
rand = "0.8.4"
byteorder = "1.4.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lib-bench"
harness = false

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 3

[package.metadata.wasm-pack.profile.release]
# `wasm-opt`. For example `['-Os']` would optimize for size while `['-O4']`
wasm-opt = ['-O4']

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false
