[package]
name = "h1emu-core"
version = "0.6.2"
edition = "2018"
[dependencies]
wasm-bindgen = "0.2.78"
getrandom = { version = "0.2.3", features = ["js"] }
rand = "0.8.4"
byteorder = "1.4.3"
[lib]
crate-type = ["cdylib"]
[profile.release]
lto = true
opt-level = 3
