[package]
name = "h1emu-core"
version = "0.1.2"
edition = "2018"
[dependencies]
wasm-bindgen = "*"
uuid = {version = "0.8.2", features = ["v4","wasm-bindgen"] }
getrandom = { version = "0.2.3", features = ["js"] }
[lib]
crate-type = ["cdylib", "rlib"]
