[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]


[tasks.build]
command = "cargo"
args = ["build","--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.wasm-test]
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build","-t","nodejs"]

[tasks.pre-publish-flow]
dependencies = [
    "format",
    "build",
    "test",
    "wasm-test"
]