[tasks.npm-publish]
script = "npm publish -p ./pkg"

[tasks.crate-publish]
command = "cargo"
args = ["publish","--allow-dirty"]

[tasks.publish-flow]
dependencies = [
    "npm-publish",
    "crate-publish"
]