name: Publish

on:
  push:
    branches: [ disabledForNow ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: wasm-pack build
      run: wasm-pack build -t nodejs
    - name: wasm-pack test
      run: wasm-pack test
    - name: wasm-pack publish
      run: wasm-pack publish
